apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-matrix
  labels:
    app: saas-matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-matrix
  template:
    metadata:
      labels:
        app: saas-matrix
    spec:
      containers:
        - name: saas-matrix
          image: 457090734537.dkr.ecr.eu-central-1.amazonaws.com/saas-matrix-project:latest
          # image: saasprojectregistry.azurecr.io/saas-matrix-project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: OMP_NUM_THREADS
              value: "1"
            - name: OPENBLAS_NUM_THREADS
              value: "1"
            - name: MKL_NUM_THREADS
              value: "1"
            - name: NUMEXPR_NUM_THREADS
              value: "1"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10